# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('usermail', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Man',
        ),
    ]
